baseurl = "https://liyuantong93.com/"
publishDir = "docs"
languageCode = "en-us"
author = "Yuantong Li"
canonifyurls = true
paginate = 10
theme = "blackburn"
copyright = "&copy; 2018 Yuantong Li. All rights reserved."
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[indexes]
  tag = "tags"
  topic = "topics"

[permalinks]
    post = "/:year/:month/:day"
    
    
[params]
    brand = "Yuantong Li"
    subtitle = "A statistics and computer science blog by Yuantong"
    dateFormat = "02 Jan 2019"
    disqus = "www-liyuantong93-com"

    # options for highlight.js (version, additional languages, and theme)
    highlight = true
    highlightjs = "Ascetic"
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "Python", "Bash"]
    highlightjsTheme = "Github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    
    
  
[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/home/"

  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-institution fa-fw'></i>"
    weight = 2
    identifier = "Posts"
    url = "/post/"

  [[menu.main]]
    name = "Talks"
    pre = "<i class='fa fa-rocket fa-fw'></i>"
    weight = 3
    identifier = "talks"
    url = "/Talks/"

  [[menu.main]]
    name = "Publications"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 4
    identifier = "research"
    url = "/Publications/"
    

[social]
  linkedin = "yuantongli"
  github = "Likelyt"
