baseurl = "https://liyuantong93.com/"
publishDir = "docs"
languageCode = "en-us"
canonifyurls = true
paginate = 10
theme = "blackburn"
googleAnalytics = "UA-166886302-1"
copyright = "&copy; 2020 Yuantong Li. All rights reserved."
ignoreFiles = ["\\.Rmd$", "\\.md$","\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
    post = "/:year/:month/:day"
    
    
[params]
    brand = "Yuantong Li"
    subtitle = "A statistics and computer science blog"
    dateFormat = "02 Jan 2006"
    disqus = "www-liyuantong93-com"

    # options for highlight.js (version, additional languages, and theme)
    highlight = true
    highlightjs = "Ascetic"
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "Python", "Bash"]
    highlightjsTheme = "Github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    
    
  
[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/home/"

  [[menu.main]]
    name = "Blog"
    pre = "<i class='fa fa-institution fa-fw'></i>"
    weight = 2
    identifier = "Blog"
    url = "/post/"

#  [[menu.main]]
#    name = "Publications"
#    pre = "<i class='fa fa-book fa-fw'></i>"
#    weight = 2
#    identifier = "publications"
#    url = "/Publications/"
  
