---
title: Options
author: Yuantong
date: '2018-07-29'
slug: options
categories:
  - Derivatives
  - Finance
  - Options
tags:
  - Derivatives
  - Finance
description: ''
topics: []
---

# 3. Options

## 3.1 Option Basic

Two Types of Options: Call (right buy) and Put (right sell).


American Options can exercise at any time up to and including expiration.


#### A. Moneyness

1. A call option is _in-the-money_ if the asset price is greater than the exercise price (i.e., if it would be worth something exercised).

2. A put option is _in-the-money_ if the asset price is less than the exercise price (i.e., if it would be worth something exercised).


3. A call option is _out-of-the-money_ if the asset price is less than the exercise price (i.e., if there is a net cost to exercising the option).

4. A put option is _out-of-the-money_ if the asset price is greater than the exercise price (i.e., if there is a net cost to exercising the option)


#### B. Option Positions and Profits at Maturity

1. _Buying_ a call option establishes a _long_ position. The holder has the right to buy at $X$. The profit at maturity is $\max(S_T-X, 0) - C$.

2. _Buying_ a put option establishes a _long_ position. The holder has the right to sell at $X$. The profit at maturity is $\max(X- S_T) - P$.

3. _Writing_ a call option establishes a _short_ position. The writer/seller is obligated to sell for $X$. The profit at maturity is $C-\max(S_T-X, 0)$.

4. _Writing_ a put option establishes a _short_ position. The writer/seller is obligated to buy for $X$. The profit at maturity is $P-\max(X-S_T, 0)$.


#### C. Intrinsic Value and Time Value

$$C = \max(S_T - X) + \text{Time Value}$$

$$P = \max(X - S_T) + \text{Time Value}$$


#### D. Contracts

Options are bought and sold in contracts. One contract is 100 options. Since one option is to buy or sell one share of stock, one option contract is to buy or sell 100 shares of stock.


#### E. Influence of Variables on Stock Option Price


| Variable             | European Call  |  European Put | American Call | American Put  |
| :------------------: |:-------------: |:-------------:|:-------------:|:-------------:| 
| Stock price          |        +       |       -       |       +       |      -        |
| Strike price         |        -       |       +       |       -       |      +        |
| Time to expiration   |        ?       |       ?       |       +       |      +        |
| Volatility           |        +       |       +       |       +       |      +        |
| Risk-free rate       |        +       |       -       |       +       |      -        |
| Dividends            |        -       |       +       |       -       |      +        |



## 3.2 Price Restriction

#### A. Upper and Lower bounds for option prices
*If there is no dividends, then European Call will be the same as the American Call.*

| Option               | Proxy          |  Min Value    | Max Value     |
| :------------------: |:-------------: |:-------------:|:-------------:|
| European Call        |        c       |max$\{S_0 - Xe^{-rT}, 0\}$|     $S_0$     |
| American Call        |        C       |max$\{S_0 - Xe^{-rT}, 0\}$|     $S_0$     |
| European Put         |        p       |max$\{Xe^{-rT} - S_0, 0\}$|   $Xe^{-rT}$  |
| American Put         |        P       |max$\{X - S_0, 0\}$       |      $X$      |





#### B. Put-Call Parity

*PSCK for European*

$$c + Xe^{-rt} = p + S_0$$

$$c + Xe^{-rt} = p + S_0 - D$$

*PSCK for American*

$$S_0 - X \leq C - P \leq S_0 - Xe^{-rT} $$


$$S_0 - X - D \leq C - P \leq S_0 - Xe^{-rT} $$






## 3.3 Option Strategies


### 3.3.1 Simple Strategies

* S + Option*

#### A. Covered Call

Covered Call = -C + S

- Income Strategy
- Outlook is neutural to bullish

#### B. Protective Put

Protective Put = S + P

- Insurance Strategy 


### 3.3.2 Spread

* Option, same type*

#### A. Bull and Bear spreads

*Bull Call spread*

- Long low $K_1$, short high $K_2$.

Profit = $\text{max}\{S_T - K_1, 0\} - C_1 - \text{max}\{S_T-K_2, 0\} + C_2$ 

*Bull Put spread*

- Long low $K_1$, short high $K_2$.

Profit = $\text{max}\{K_1 - S_T, 0\} - P_1 - \text{max}\{K_2 - S_T, 0\} + P_2$ 

*Bear Put spread*

- Long high $K_2$, short low $K_1$.

Profit = $\text{max}\{K_2 - S_T, 0\} - P_2 - \text{max}\{K_1 - S_T, 0\} + P_1$ 


*Bear Call spread*

- Long high $K_2$, short low $K_1$.

Profit = $\text{max}\{S_T - K_2 , 0\} - C_2 - \text{max}\{S_T - K_1 , 0\} + C_1$ 


#### B. Butterfly spreads

- Long $K_1$, Long $K_2$, short 2 $\frac{K_1+K_2}{2}$.

Expects low Volatility

Capped Risk

#### C. [Calendar spreads](https://www.investopedia.com/terms/c/calendarspread.asp)



#### D. [Diagonal spreads](https://www.investopedia.com/university/optionspreadstrategies/optionspreads6.asp)



### 3.3.3 Combination

* Option, different*

#### A. Straddle and Strangle

- Taking a position in both calls and puts on the same stock.

*Straddle*

- A call and a put

- Same strike price

- Direction neutral

- Wants volatility


*Strangle*

- A call and a put

- Different strike prices

- Like straddle, but cheaper


*Strip*


- Two puts and a call

- Bet on volatility

- More Bearish



*Strap*

- Two calls and a put

- Bet on volatility

- More Bullish


### 3.3.4 Exotic Options


## 3.4 Greeks

### 3.4.1 Delta

The Delta of a European call option is the rate of change of its value with respect to the underlying security price:

$$\Delta = \frac{\partial f }{\partial S} = \Phi (d_1) \text{or } \Phi (d_1) - 1 $$

The range is $-1 \leq \Delta \leq 1$.


*Delta is additive*

a Long Call + Short Put = Long stock,

Call Delta + Delta of a Short Put = Stock Delta (Delta of a short put = - delta of a long put)




*Probability explanation*

Call deltas can be interpreted as the probability of the option finishing in-the-money. For this reason, a deep in-the-money option will have a delta close to 1, and a deep out-of-the-money option will have a delta close to 0.

*Time*

When $t \rightarrow T$, delta is unstable.


#### A. *Slope of call option*

#### B. *CDF of Normal Distribution*

#### C. *Hedge ratio*

[Delta neutral](https://www.investopedia.com/terms/d/deltahedging.asp): [Dynamic aspects of delta hedge](https://www.glynholton.com/notes/dynamic_hedging/)



### 3.4.2  Gamma: The convexity factor


The Gamma $\Gamma$ of a derivative is the sensitivity of $\Delta$ with respect to $S$:

$$\Gamma = \frac{\partial^2 f}{\partial S^2} =\frac{N^{'}(d_1)}{S \sigma \sqrt{T}} =\frac{1}{S \sqrt{2\pi} \sigma \sqrt{T-t}} \exp(-\frac{d_1^2}{2})$$

Range: $0 \rightarrow + \rightarrow 0$  
Since long call or put option are both convex (larger than 0). It is a pdf of normal distribution. So when Gamma is the largest, an option is at the money. 

When you long a call or put, you prefer the Gamma as large as possible. 

*Time*

when $t \rightarrow T$, Gamma increases. Peak higher.


##### A. *Summary*

(1) Long Call: $\Delta > 0, \Gamma > 0$

(2) Long Put: $\Delta < 0, \Gamma > 0$

(3) Short Call: $\Delta < 0, \Gamma < 0$

(4) Short Put: $\Delta > 0, \Gamma < 0$

##### B. *Taylor expansion*

$$ df  = \Delta dS + \frac{1}{2} \Gamma (dS)^{2}$$ 


##### C. Gamma Neutral Position

[Gamma Neutral](https://www.investopedia.com/terms/g/gammaneutral.asp)



### 3.4.3 Vega:  The volatility factor

The Vega ($\nu$) of a derivative security is the rate of change of value of the derivative with respect to the volatility of the underlying asset.

$$\nu = \frac{\partial C}{\partial T} = \frac{\partial P}{\partial T} = S \sqrt{T} N^{'}(d_1)$$

+ Most sensitive to changes to volatility when they are at the money.

+ when $t \rightarrow T$, Vega increases, larger since uncertainty higher.


### 3.4.4 Theta:  The time decay factor

This [definition](http://www.math.unl.edu/~sdunbar1/MathematicalFinance/Lessons/BlackScholes/Greeks/greeks.pdf) is the rate of change with respect to the real (or calendar) time.

$$\Theta = \frac{\partial f}{\partial T}$$

+ For long position, theta<0, means option lose value as time goes by. (negative approximate pdf of normal distribution)

+ when $t \rightarrow T$, Vega increases, larger (-) since decay faster.


### 3.4.5 Rho: The interest rate factor

The rho ($\rho$) of a derivative security is the rate of change of the value of the derivative security with respect to the interest rate.

$$\rho   = \frac{\partial f}{\partial r} = X e^{(-rT)} T N(d_2), \text{when put, it is negative}$$

+ Not sensitive 



### 3.4.6 Summary

Note that the Black-Scholes partial differential equation can now be written as

$$rf =  \Theta + r S \Delta + \frac{1}{2}\sigma^{2} S^2 T $$

You can find something [here](https://www.riskprep.com/component/exam/?view=exam&layout=detail&id=55).


The price $f$ of an option (or combination of options) depends on:

| BS Factor            | Greek                                             | 
| -------------        |:-------------:             					   | 
| Share price, $S$     | $\Delta = \frac{\partial f}{\partial S}$          | 
| Gamma, convexity     | $\Gamma = \frac{\partial^2 f}{\partial S^2}$      | 
| Volatility, $\sigma$ | $\nu    = \frac{\partial f}{\partial \sigma}$     |    
| Time, $T$            | $\Theta = \frac{\partial f}{\partial T}$     	   |              
| Risk free rate, $r$  | $\rho   = \frac{\partial f}{\partial r}$          |              
## 3.5 Binomial Trees

*1. riskless hedge portfolio*

We compute a price for the option by constructing a riskless hedge portfolio. Thus form a portfolio that is long $\Delta$ shares of stock and short one call option. The cost to set up the portfolio and its value at the end of one time step are depicted on the following tree.

$$\Delta S_u - C_u = \Delta S_d - C_d$$

$$\Delta = \frac{C_u - C_d}{S_u - S_d} $$
Thus the option prict will be $\Delta S_0 - C = e^{-rT}\{\Delta S_u - C_u\}$

$\Delta = [pC_u+(1-p)C_d]e^{-rt}$

where $p = \frac{e^{rt}-d}{u-d}$, $t$ is for each step of the binomial tree. Sometimes the $u=\frac{S_u}{S_0}$ and $d = \frac{S_d}{S_0}$ will be given, and sometime the $u = e^{\sigma \sqrt{\Delta t}}$ and $d =\frac{1}{u}$. 


*2. Pricing American Options:*

We can use binomial trees to price American options. The procedure is to work backward through the tree, testing at each node whether it is optimal to exercise the option.


*3. Comparison of Binomial and Black-Scholes Option Prices*

Analysts use the binomial model to price American options and other, more complicated derivatives. One reason is that the Black-Scholes model assumes the option is European and can only be exercised at maturity. This is not typically a disadvantage when pricing American call options because call options are typically worth more alive than dead. The Black-Scholes model does a poor job pricing American put options because it is often optimal to exercise an American put before expiration.

 We expect the American binomial call option price to converge to the Black-Scholes call option price as the number of time steps ($\Delta t$) in the binomial tree gets large. However, we expect the Black-Scholes model to _underprice_ the American put option because the Black-Scholes model does not allow for optimal early exercise of the option.


## 3.6 Stochastic Calculus

*1. Wiener Processes*

Stochastic variable $\bar{\varepsilon}(t)$ have the following properties:

(1) $\bar{\varepsilon}(t) \sim N(0,1)$

(2) For any two times, $t_i$ and $t_j$, $i\neq j$ , the covariance (and therefore correlation) between $t_i$ and $t_j$ is zero.

Thus $\bar{\varepsilon}(t)$ has the same distribution for all t (is stationary) and values for $\bar{\varepsilon}(t)$ at any two points in time are statistically independent.


*1.1 basic Wiener process:*

$$d\bar{z} =\bar{\varepsilon}\sqrt{dt}$$

With mean 0, variance $t$.


*1.2 General Wiener process or arithmetic Brownian motion:*

The general Wiener process $\bar{x}$ is described by the following stochastic differential equation which is often used as a model for the rate of return on stock:

$$d\bar{x}  = a dt + b d\bar{z}$$

Where $E[d\bar{x}] = adt, Var(d\bar{x}) = b^2dt, Cov(d\bar{x}_s, d\bar{x}_t) = 0$


*2. Ito Processes*

$$d\bar{x}  = a(x,t) dt + b(x,t) d\bar{z}$$

*3. Geometric Brownian Motion*
Consider a process $x_t$ described by arithmetic Brownian motion with drift $\mu$ and variance $\sigma^2$. The process $y_t$ is geometric Brownian motion if

$$y_t = e^{x_t}$$

The stochastic differential equation for geometric Brownian motion is:

$$d\bar{y} =  \alpha y_tdt + \sigma y_t d\bar{z}$$

_Properties of geometric Brownian motion_:


(1) The drift parameter $\alpha$ is related to the parameters of a corresponding arithmetic Brownian motion process by the relation $\alpha = \mu + \sigma^2 /2$.

(2) Geometric Brownian motion is a special case of a more general Itô process. An Itô process $y_t$ is described by the stochastic differential equation (SDE): $d\bar{y}  = \mu(y_t,t) dt + \sigma(y_t,t) d\bar{z}$, where the drift and volatility rate are function of $y_t$ and $t$. Obviously, geometric Brownian motion is an Itô process with $\mu(y_t,t) = \alpha y_t$ and $\sigma(y_t,t) = \sigma y_t$.

(3) Geometric Brownian motion has the property that the process $y_t$ is absorbed at zero. As such, if $y_t$ ever reaches zero it will stay at zero. This is not the case for arithmetic Brownian motion, since the process $x_t$ can wander (diffuse) above and below zero.

(4) Arithmetic Brownian motion is an inappropriate process for financial asset prices. The reason is two-fold. First, the process admits negative prices. Second, the process does not have the property that the expected percentage return on the asset is independent of the level of the price.


*4. Fundamental Theorem of Stochastic Calculus*

Consider an Itô process:

$$dx  = \mu(x,t) dt + \sigma(x,t) dz$$

where $dz = \varepsilon \sqrt{dt}, \varepsilon \sim iid N(0,1)$,is the increment of a standard Wiener process.



### Itô’s Lemma

If $F(x,t)$ is a twice continuously differentiable function of $x$ and a once continuously differential function of $t$, then the total differential $F$ is given by

$$dF = \frac{\partial F}{\partial t}dt + \frac{\partial F}{\partial x}dx + \frac{1}{2} \frac{\partial^2 F}{\partial x^2}(dx)^2$$


where $dz^2 = E[dz^2] = dt, w.p.1$ and $(dz)^2 = (\varepsilon_t \sqrt{dt})^2 = \varepsilon_t^2 dt$ is equal to $dt$.


## 3.7 B-S Model

*1. Assumption*

(1) The underlying asset, $S_t$ , can be bought and sold in fractions of units. The asset pays no dividends or other distributions before the option’s expiration date.

(2) The risk-free interest rate, $r$, is a constant and the same for all maturities.

(3) The option is European, with exercise price $X$ and time to expiration $T$.

(4) There are no frictions in the market place such as taxes, transaction costs, or margin requirements. Trading in the underlying asset is continuous.

(5) The asset price dynamics are described by geometric Brownian motion:

$$dS_t = \alpha S_t dt + \sigma S_tdz$$

*2. Deriving the B-S Call Option Formula*

Denoting $C(S_t, t)$ as the price of a European call option, we may use Itô's Lemma to compute the instantaneous change in the option price as

$$dC = \frac{\partial C}{\partial t}dt + \frac{\partial C}{\partial x}dx + \frac{1}{2} \sigma^2 S_t^2\frac{\partial^2 C}{\partial S^2}(dt)^2$$

Since $(dS)^2 = \sigma^2 S_t^2 dt$.

The value of the hedge portfolio is

$$\Pi =  \frac{\partial C}{\partial S} S_t- C(S,t)$$

The change in the value of the hedge portfolio is given by


$$d\Pi =  \frac{\partial C}{\partial S} dS- dC$$

Then which upon substitution for $dC$ from above gives

$$d\Pi = -(\frac{\partial C}{\partial t} + \frac{1}{2} \sigma^2 S_t^2 \frac{\partial^2 C}{\partial S^2})dt$$

With the terms involving $dS$ cancelling out, the hedge portfolio is riskless because dS is the only term which is a function of $dz$. Therefore the hedge portfolio should earn the risk-free rate of interest $r$ per unit time. Thus we have 

$$\frac{d\Pi}{\Pi} = r dt \hspace{3mm} \text{or} \hspace{3mm} d\Pi = r \Pi dt$$

$$ -(\frac{\partial C}{\partial t} + \frac{1}{2} \sigma^2 S_t^2 \frac{\partial^2 C}{\partial S^2})dt = r (\frac{\partial C}{\partial S}S_t - C(S_t,t))dt$$

or after cancelling $dt$ on both sides of the equation and moving all terms to the right- hand-side of the equation we get

$$\frac{1}{2} \sigma^2 S_t^2 \frac{\partial^2 C}{\partial S^2} + r S_t \frac{\partial C}{\partial S} + \frac{\partial C}{\partial t} - rC = 0$$

Thus the call option value, $C(S_t,t)$, must satisfy a second-order partial differential equation (PDE). In order to solve the PDE, we need three boundary conditions. We must specify what happens to the option value at expiration, what happens before that time when $S_t$ becomes arbitrarily low, and what happens when $S_t$ becomes arbitrarily high.

For a European call option, the boundary conditions are:

(1) At expiration $C(S_T,T) = \max (S_T - X)$.

(2) At $S_T = 0, C(0,t) = 0$

(3) As $S_t \rightarrow \infty, \partial C / \partial S \rightarrow 1$.


*3. The B-S Call and Put Formulas*

The Black-Scholes equation for the value of a European call option is
$$C = S_0 N(d1) - Xe^{-rT} N(d_2)$$
where $d_1 = \frac{\ln(\frac{S_0}{X})+(r+\frac{\sigma^2}{2})T}{\sigma \sqrt{T}}$ and $d_2 = \frac{\ln(\frac{S_0}{X})+(r-\frac{\sigma^2}{2})T}{\sigma \sqrt{T}} = d_1 - \sigma \sqrt{T}$

and $N(x)$ is the cumulative standard normal distribution function.


_Comments_:

(1) The formula can be interpreted as follows. If the call is exercised on the expiration date, the holder will receive $S_T$ and pay $X$. However, this will take place only if $S_T>X$ . Thus, $S_0N(d_1)$ is the present value of receiving $S_T$ conditional on $S_T>X$; and $-X e^{-rT}N(d_2)$ is the present value of paying $X$ conditional on $S_T < X$. Consistent with this interpretation, if the stock price gets large relative to $X$ (and the option is deep in the money), $N(d1)\approx N(d2)\approx 1.0$ and $C \approx S_0 - Xe^{-rt}$.

(2) The B-S European call option model can also be used to price American call options. As we proved earlier, except for the effect of dividend payout, it is never optimal to exercise an American call early, so that American and European calls on non-dividend- paying stocks should have the **same** value.

(3) the delta of a call option is

$$\Delta_c = \frac{\partial C}{\partial S} = N(d_1) > 0$$

*B-S Put Formula:* 

$$P =  Xe^{-rT} N(-d_2) - S_0 N(-d_1)$$

_Comments_:

(1) The put formula is less useful than the call formula because, unlike the American call, it is optimal to exercise American puts before expiration. The B-S put equation does not take account of the economically valuable right to exercise early, and so it **undervalues** American puts.

(2) $\Delta_p = \Delta_c - 1$


(3) Or use **PSCK**

$$S_0^{*} = S_0 -PV(D)$$

*4. Adjusting the Black-Scholes Model for Dividends*

## 3.8 Quantifying Volatility

*1. Historical - Based Approach*

Use daily return (in log) to compute $\nu^2 = sum/(n-1)$. Then $\sigma^2 = (252) * \nu^2$. In practice, volatility is estimated for most stocks using 1 to 6 months of daily prices.

#### A. Parametric model

(1) EWMA

(2) GARCH

#### B. Nonparametric approach

(1) Historical Simulation

(2) Multivariate Density Estimation (MDE)


#### C. Hybrid approach

*2 Implied Volatility - Based Approach*

An alternative volatility estimation procedure arises from the option pricing model itself. Since all of the parameters of the option pricing model, except $\sigma$, are known or can be estimated with little uncertainty, one needs only to equate the observed market price of the option, $C_m$ , with its formula value, $C$, and solve for the volatility,$\sigma$, that equates two values.


An analytical expression for the variance parameter cannot be derived; however, accurate approximation is possible through numerical procedures.

_Problem:_

The Black-Scholes model assumes that volatility is constant, and does not depend on maturity, exercise price, or whether the option is a call or a put. All options written on the same underlying stock will yield identical estimates of volatility. This is not the case! Possible reasons include:

(1) **Non-Simultaneity of Prices**. Estimating the implied volatility assumes that the option price and the stock price are observed at the same instant in time. Frequently, we only have the prices of the option and the stock at the times at which they were last traded. It is unlikely that these trades, one in the option market and one in the stock market, occurred at the same instant, and, to the extent that they are not contemporaneous, there will be error in the estimate of volatility.

(2) **Bid-Ask Prices**. Even if the option and the stock price observations used to compute implied volatility are simultaneous, there is a problem with what the prices represent. When market orders are executed, they are at the bid or the ask price, depending upon whether the individual entering the market to trade wanted to sell (bid) or buy (ask). Since we generally do not know the motivation of the trader who was involved in the last observed transaction, implied volatility estimates have error when the bid price of the option is matched with the ask price of the stock and vice versa.


(3) **Model Mis-Specification**. The implied volatility technique assumes that the option pricing model used to compute $\sigma$ is correctly specified. If it is not, then there is obviously going to be error in the estimate of $\sigma$. Model assumptions that can be violated include lognormally distributed stock prices and no early exercise of the option.


*Volatility Surface*

A plot of the implied volatilities of options written on the same underlying stock as a function of their strike prices produces what is called a volatility surface. The pattern that is often produced is referred to as a volatility smile, skew (sloppy smile), or smirk.

The typical pattern is that **volatility decreases as the strike price increases**. In addition, the implied volatility curve is flatter for longer maturity options.



















